### PR TITLE
update Progress Bar, define maxValue at initialization

### PR DESCRIPTION
**Pull request by jackchoon**

### CODE REVIEW

**Comment by nathanpeck** [comment]
Thanks for providing this. However, I can not merge this in as is because it completely removes the ability to update the max value dynamically.

In some workloads the total amount of work can not be accurately determined in advance, and it is necessary to update the max value on the fly, allowing the progress bar to skip ahead or move backwards as the workload is either expanded or decreased.

I think an acceptable solution would be to allow the user to setup a predefined max value on the constructor if they wish and then optionally leave out the max value when calling `ProgressBar.update()`, but also retain the ability to change the max value in the `ProgressBar.update()` method if needed. If you update your pull request with this change I will definitely merge it in.

Thanks!

**Comment by jackchoon** [comment]
Thanks for considering and suggestion. I will make an improvement on it. Do you think a 'percentage' is acceptable when update ? 
```
ProgressBar.update( percent )
```

**Comment by artokun** [comment]
Due to potential conflicts with backwards compatibility the percent change will not work. I could probably make a new PercentBar module that will work the way you would intend it to. I'd have to loop in the creator if that is something he'd like to add. @nathanpeck @jackchoon

**Comment by artokun** [comment]
This functionality is now available in v0.3.6
`.update(currentValue, maxValue)` and `.update(percent)`

**Pull request closed without merging**
